version: 48
jobs:
- name: pull
  steps:
  - type: PullRepository
    name: pull
    remoteUrl: http://localhost:6610/test
    userName: admin
    refs: refs/tags/*
    withLfs: false
    force: false
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 0 * * * * ?
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
- name: post tag
  steps:
  - type: CommandStep
    name: build
    runInContainer: true
    image: alpine
    interpreter:
      type: DefaultInterpreter
      commands: |
        echo @tag@ is created
    runAs: 0:0
    useTTY: true
    condition: SUCCESSFUL
    optional: false
  triggers:
  - type: TagCreateTrigger
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 14400
